version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: Docker_Files/Dockerfile
    container_name: my_app
    working_dir: /app
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8000)); s.close(); sys.exit(0)\""]
      interval: 10s
      timeout: 3s
      retries: 10